version: '3'

services:
  db:
    image: mysql:latest
    container_name: realty_db
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./server/schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: realty

  realty-server:
    container_name: realty-server
    restart: on-failure
    build:
      context: .
      dockerfile: server/Dockerfile
    depends_on:
      - db
    ports:
      - "4000:4000"

  frontend:
    container_name: client
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - realty-server

volumes:
  mysql-data: